### ISSUE TITLE
Problems about tRFA

### ISSUE THREAD

**Issue by JSparks7** [krishnap25/tRFA#3]
Hello, when I ran the femnist task of Torch version tRFA, I encountered an error：
`Traceback (most recent call last):`
`File "main.py", line 921, in <module>`
`    main()`
`  File "main.py", line 101, in main`
`    clients, corrupted_client_ids = setup_clients(args.dataset, model_name=args.model,`
`  File "main.py", line 611, in setup_clients`
`    users = rng_sub.sample(users, 1000)`
`  File "/root/miniconda3/envs/rfa/lib/python3.8/random.py", line 363, in sample`
`    raise ValueError("Sample larger than population or is negative")`
`ValueError: Sample larger than population or is negative`
I only encountered this problem in the femnist task. The sent140 task can run normally and print the log results.
How can I solve the femnist problem?
Also, it seems that there is no startup script for the Shakespeare task in tRFA

**Comment by krishnap25** [comment]
I am not able to reproduce this issue locally. Can you please give me some diagnostics, e.g. `len(users)` in the line before this error? A potential solution is to delete all the data files and download the data again.

The Shakespeare task is not supported in this repo, please refer to the [tensorflow implementation](https://github.com/krishnap25/RFA).

I would also suggest switching to [this modern PyTorch FL simulation repo](https://github.com/facebookresearch/FL_partial_personalization), as it can seamlessly support larger models or datasets. While it does not have robust aggregation implemented, that is quite easy to add with the [geom-median](https://github.com/krishnap25/geom_median) package.

**Comment by JSparks7** [comment]
`############################## femnist.erm_log_reg ##############################`
`Obtained Model Path : femnist.erm_log_reg`
`Namespace(aggregation='geom_median', batch_size=10, clients_per_round=100, corruption=None, data_dir='../', dataset='femnist', decay_lr_every=200, eval_every=50, fraction_corrupt=0.1, fraction_to_discard=0, full_record=False, gpu=None, lr=1.0, lr_decay=1.0, make_iid=False, minibatch=None, model='erm_log_reg', no_logging=False, norm_bound=1000000.0, num_epochs=1, num_rounds=2000, old_validation=False, output_stat_file='metrics/stat_metrics.csv', output_summary_file='outputs/emnist/outputs_gm_clean_1', output_sys_file='metrics/sys_metrics.csv', patience_iter=20, reg_param=1e-09, safety_user_level=None, seed=1, split_by_user=False, t='large', validation=False, weiszfeld_maxiter=2)`
`***** using a max batch size of 1000000000`
`***** using a max batch size of 1000000000`
`Loading data from path: ../`
`reading train file ../data/femnist/data/train/all_data_0_niid_0_keep_100_train_9.json`
`reading train file ../data/femnist/data/train/all_data_1_niid_0_keep_100_train_9.json`
`reading train file ../data/femnist/data/train/all_data_2_niid_0_keep_100_train_9.json`
`reading train file ../data/femnist/data/train/all_data_3_niid_0_keep_100_train_9.json`
`reading train file ../data/femnist/data/train/all_data_4_niid_0_keep_100_train_9.json`
`reading train file ../data/femnist/data/train/all_data_5_niid_0_keep_100_train_9.json`
`reading train file ../data/femnist/data/train/all_data_6_niid_0_keep_100_train_9.json`
`reading train file ../data/femnist/data/train/all_data_7_niid_0_keep_100_train_9.json`
`reading test file ../data/femnist/data/test/all_data_0_niid_0_keep_100_test_9.json`
`reading test file ../data/femnist/data/test/all_data_1_niid_0_keep_100_test_9.json`
`reading test file ../data/femnist/data/test/all_data_2_niid_0_keep_100_test_9.json`
`reading test file ../data/femnist/data/test/all_data_3_niid_0_keep_100_test_9.json`
`reading test file ../data/femnist/data/test/all_data_4_niid_0_keep_100_test_9.json`
`reading test file ../data/femnist/data/test/all_data_5_niid_0_keep_100_test_9.json`
`reading test file ../data/femnist/data/test/all_data_6_niid_0_keep_100_test_9.json`
`reading test file ../data/femnist/data/test/all_data_7_niid_0_keep_100_test_9.json`
`len(users):`
`799`
`Traceback (most recent call last):
  ...
  File "main.py", line 101, in main
    clients, corrupted_client_ids = setup_clients(args.dataset, model_name=args.model,
  File "main.py", line 613, in setup_clients
    users = rng_sub.sample(users, 1000)
  ...
ValueError: Sample larger than population or is negative`

Therefore, by printing the length of users, we can see that `len(users)` is 799, which does not reach 1000. By opening the json file, you can see that there are 100 users in a json, so is it caused by incomplete download of my data set?

**Comment by krishnap25** [comment]
Yes, I would delete and download the dataset again as a potential fix. We
should have >3000 users in this dataset.
